url: 'http://localhost:8000/public/graphql/v1readonly'
headers:
  X-Hasura-Admin-Secret: gelsemium
  X-Hasura-Role: user
  X-Hasura-User-Id: 1
  Content-Type: application/json
  Accept-Encoding: gzip
# "Debug" mode enables request and response logging for Autocannon and K6
# This lets you see what is happening and confirm proper behavior.
# This should be disabled for genuine benchmarks, and only used for debugging/visibility.
debug: false
queries:
  # Name: Unique name for the query
  # Tools: List of benchmarking tools to run: ['autocannon', 'k6', 'wrk2']
  # Execution Strategy: the type of the benchmark to run. Options are:
  # REQUESTS_PER_SECOND: Fixed duration, fixed rps. Example parameters:
  #   duration: 10s
  #   rps: 500
  # FIXED_REQUEST_NUMBER: Complete requests as fast as possible, no duration. Example parameters:
  #   requests: 10000
  # MAX_REQUESTS_IN_DURATION: Make as many requests as possible in duration. Example parameters:
  #   duration: 10s
  # MULTI_STAGE: (K6 only currently) Several stages of REQUESTS_PER_SECOND benchmark. Example parameters:
  #   initial_rps: 0
  #   stages:
  #     - duration: 5s
  #       target: 100
  #     - duration: 10s
  #       target: 1000
  # CUSTOM: Pass completely custom options to each tool (see full API spec for all supported options, very large)
  - name: List-Customer-Cached
    tools: [k6]
    execution_strategy: FIXED_REQUEST_NUMBER
    requests: 50000
    connections: 100
    query: |
      query MyQuery @cached(ttl: 60) {
        customer(limit: 100}) {
          id
          last_name
          first_name
        }
      }
  - name: List-Customer-Large-Batch-Cached
    tools: [k6]
    execution_strategy: FIXED_REQUEST_NUMBER
    requests: 15000
    connections: 100
    query: |
      query MyQuery @cached(refresh: false) {
        customer(limit: 10000}) {
          id
          last_name
          external_ref_list
          date_of_birth
          created_at
          first_name
          updated_at
        }
      }
  - name: List-Customer-Slow-Query-Cached
    tools: [k6]
    execution_strategy: FIXED_REQUEST_NUMBER
    requests: 50000
    connections: 100
    query: |
      query MyQuery @cached {
        customer(offset: 750000, limit: 25) {
          id
          last_name
          created_at
          first_name
          updated_at
        }
      }
  - name: List-Customer
    tools: [k6]
    execution_strategy: FIXED_REQUEST_NUMBER
    requests: 50000
    connections: 100
    query: |
      query MyQuery {
        customer(limit: 100}) {
          id
          last_name
          first_name
        }
      }
  - name: List-Customer-Large-Batch
    tools: [k6]
    execution_strategy: FIXED_REQUEST_NUMBER
    requests: 4000
    connections: 100
    query: |
      query MyQuery {
        customer(limit: 10000}) {
          id
          last_name
          external_ref_list
          date_of_birth
          created_at
          first_name
          updated_at
        }
      }
  - name: List-Customer-Slow-Query
    tools: [k6]
    execution_strategy: FIXED_REQUEST_NUMBER
    requests: 2000
    connections: 100
    query: |
      query MyQuery {
        customer(offset: 750000, limit: 25) {
          id
          last_name
          created_at
          first_name
          updated_at
        }
      }
