# this is an example docker-compose.yml file to run the graphql-engine-plus image
version: '3.6'
services:
  postgres:
    image: postgres:13.4-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: example_graphql_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGUSER: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "--quiet"]
      interval: 5s
      timeout: 3s
    ports:
      - "5432:5432"
  redis:  # port 6379, 8001 -> Redis Insight UI
    image: redis/redis-stack:latest
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
      - "8001:8001"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 5s
      timeout: 3s
  jaeger:  # this include OTEL collector
    image: jaegertracing/all-in-one
    ports:
      - "16686:16686"  # expose Jaeger UI to display traces
    environment:
      - LOG_LEVEL=debug
  graphql-engine:
    image: graphql-engine-plus:latest
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./example/graphql-engine/schema:/graphql-engine/schema
      - ./example/graphql-engine/scripts:/graphql-engine/scripts
    env_file:
      - ./.env
  # runner:
  #   image: apprunner-example:latest
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     redis:
  #       condition: service_healthy
  #   env_file:
  #     - ./.env
volumes:
  db_data:
    driver: local
  redis-data:
    driver: local