version: 3
endpoint: http://localhost:8000/public/meta/
admin_secret: gelsemium
metadata_directory: metadata
migrations_directory: migrations
actions:
  kind: synchronous
  handler_webhook_baseurl: http://localhost:8880/execute